menu:
  Example: /example/markdown.html
  Guide: /guide
  API: /api/classes/MyClass.html
  Blog: /blog/

example_siderbar:
  markdown: Markdown Editor
  modal: Modal Component
  pager: Linked Pager
  performance: Performance
  slider: Simple Slider
  todomvc: Todomvc

global_link:
  guide: /guide
	

swiftype_key: fDxc-hEngMPFuZ1VP_FJ
twitter: regularjs
github: regularjs/regular
