menu:
  Example: /example/markdown.html
  Guide: /guide
  Reference: /api/
  Blog: /blog/
  Github: https://github.com/regularjs/regular

example_siderbar:
  markdown: Markdown Editor
  modal: Modal Component
  pager: Linked Pager
  performance: Performance
  slider: Simple Slider
  todomvc: Todomvc

global_link:
  guide: /guide
	

swiftype_key: fDxc-hEngMPFuZ1VP_FJ
twitter: regularjs
github: regularjs/regular
google_analytics: UA-54220110-1
